#!/usr/bin/env python3
"""Regenerate the workstream index inside dev/active/OPEN-TASKS.md.

Why this exists
---------------
On 2026-09-08 the founder asked what the full task list was. There were three
files each behaving as though it were the answer: `OPEN-TASKS.md`, which said in
its own header that it superseded the handovers; `2026-08-19-master-task-list.md`,
recorded elsewhere as THE task file; and `video-analysis/tasks.md`, a 56-item
feature plan neither of the others mentioned.

The consequence was not abstract. Asked whether video analysis was planned, I
read the register, searched narrowly, and told him it was not in the pipeline.
It was — six documents, two rounds of expert review, and a passed GO/NO-GO.

A hand-maintained index would drift the same way within a fortnight, so this
generates it. Counts come from the files themselves; the last-touched date comes
from git, because a workstream with 81 open items and no commits for three weeks
is telling you something a count alone hides.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INDEX = ROOT / "dev/active/OPEN-TASKS.md"
START = "<!-- TASK-INDEX:START -->"
END = "<!-- TASK-INDEX:END -->"

# Below this, a file is a note that happens to contain checkboxes rather than a
# workstream. Listing those would bury the real ones.
MIN_ITEMS = 5

MARKER = re.compile(r"^\s*- \[([ x~!])\]", re.M)


def counts(path: Path) -> dict[str, int]:
    text = path.read_text(encoding="utf-8", errors="replace")
    found = MARKER.findall(text)
    return {
        "open": found.count(" "),
        "prog": found.count("~"),
        "blocked": found.count("!"),
        "done": found.count("x"),
    }


def last_touched(path: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, check=False,
        )
        return (out.stdout or "").strip() or "—"
    except Exception:
        return "—"


def build() -> str:
    rows = []
    for path in sorted(ROOT.glob("dev/**/*.md")):
        if path == INDEX:
            continue
        c = counts(path)
        total = sum(c.values())
        if total < MIN_ITEMS:
            continue
        live = c["open"] + c["prog"] + c["blocked"]
        rows.append((live, path, c))

    # Live work first; a finished workstream is history, not a queue.
    rows.sort(key=lambda r: (-r[0], str(r[1])))

    tot = {k: sum(c[k] for _, _, c in rows) for k in ("open", "prog", "blocked", "done")}
    lines = [
        START,
        "",
        f"**{len(rows)} workstreams · {tot['open']} open · {tot['prog']} in progress · "
        f"{tot['blocked']} blocked · {tot['done']} done.**",
        "",
        "Generated by `dev/scripts/task-index.py` — do not hand-edit between the",
        "markers. Counts are read from each file; the date is its last commit, so a",
        "workstream with many open items and an old date is stalled, not busy.",
        "",
        "| Workstream | Open | In progress | Blocked | Done | Last touched |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for live, path, c in rows:
        rel = path.relative_to(ROOT)
        name = f"[{rel.parent.name if rel.parent.name != 'active' else rel.stem}]({rel})"
        flag = " ⚠" if c["blocked"] else ""
        lines.append(
            f"| {name}{flag} | {c['open']} | {c['prog']} | {c['blocked']} | {c['done']} | {last_touched(path)} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    # `--check` writes nothing and fails when the index is stale. The suite runs
    # it, so an added workstream cannot sit outside the index the way
    # video-analysis did for a week.
    check = "--check" in sys.argv
    text = INDEX.read_text(encoding="utf-8")
    block = build()
    if START in text and END in text:
        new = re.sub(
            re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S
        )
    else:
        new = text.rstrip() + "\n\n## Every workstream\n\n" + block + "\n"
    if new != text:
        if check:
            print("task-index: STALE — run: python3 dev/scripts/task-index.py")
            return 1
        INDEX.write_text(new, encoding="utf-8")
        print(f"task-index: updated {INDEX.relative_to(ROOT)}")
    else:
        print("task-index: already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
